-- Начальный набор слов (20+ слов)
INSERT INTO word_pool (english_word, russian_translation, added_by) VALUES
('peace', 'мир', NULL),
('hello', 'привет', NULL),
('world', 'мир', NULL),
('green', 'зеленый', NULL),
('white', 'белый', NULL),
('black', 'черный', NULL),
('red', 'красный', NULL),
('blue', 'синий', NULL),
('yellow', 'желтый', NULL),
('car', 'машина', NULL),
('house', 'дом', NULL),
('dog', 'собака', NULL),
('cat', 'кошка', NULL),
('book', 'книга', NULL),
('pen', 'ручка', NULL),
('computer', 'компьютер', NULL),
('water', 'вода', NULL),
('fire', 'огонь', NULL),
('earth', 'земля', NULL),
('sun', 'солнце', NULL),
('moon', 'луна', NULL),
('star', 'звезда', NULL),
('tree', 'дерево', NULL),
('flower', 'цветок', NULL),
('school', 'школа', NULL),
('teacher', 'учитель', NULL),
('student', 'ученик', NULL),
('friend', 'друг', NULL),
('family', 'семья', NULL),
('food', 'еда', NULL)
ON CONFLICT (english_word) DO NOTHING;